# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# baseurl: /beringseaversus.me
# url: "http://yourdomain.com" # the base hostname & protocol for your site

port:         9876
source:       devel
destination:  deploy
markdown:     kramdown
exclude:      ['node_modules', '.gitignore', 'gulpfile.js', 'package.json', 'bower.json', 'gulp', 'Gemfile', 'Gemfile.lock', 'feed.xml', 'page-with-example-code.html', npm-shrinkwrap.json, '**/*.sass', '**/*.scss', '_pages/**/main.css']
include:      ['.htaccess']
incremental:  false
collections:
  companies:
    output: true # this generates a page for each collection

url: https://beringseaversus.me
compress_html:
  blanklines: true

defaults:
  -
    scope:
      type:       "pages"
    values:
#      permalink:  /pages/
      layout:     page
  -
    scope:
      type:       "posts"
    values:
      permalink:  /blog/:categories/:title/
      layout:     post
  -
    scope:
      type:       "companies"
    values:
      permalink: /collections/:collection/:name/
      layout: company
