var vars = require('./vars'),
	gulp = require('gulp'),
	duplicate = require('gulp-rename'),
	gzip = require('gulp-gzip'),
	localServer = require('gulp-connect'),
	concat = require('gulp-concat'),
	uglifyJs = require('gulp-uglify'),
	checkJs = require('gulp-jshint');

gulp.task('process-scripts', function() {
	return gulp.src([
		vars.paths.scripts.src
	])
	.pipe(concat(vars.renderedNames.javascript.myJs))
	.pipe(checkJs())
	.pipe(gulp.dest(vars.paths.scripts.dest))
	.pipe(duplicate({suffix: '.min'}))
	.pipe(uglifyJs())
	.pipe(gulp.dest(vars.paths.scripts.dest))
	.pipe(gzip())
	.pipe(gulp.dest(vars.paths.scripts.dest))
	.pipe(localServer.reload());
});

gulp.task('modernizeJs', function() {
	return gulp.src(vars.watchedJsFiles)
	.pipe(modernizeJs())
	.pipe(uglifyJs())
	.pipe(gulp.dest(vars.paths.scripts.src + 'autogenerated/'));
});
