var assetsSrc = 'assets/';
var bower = assetsSrc + '/_bower_components/';


var paths = {

	// html: {
	//     src: srcJekyll + '**/*.html',
	//     dest: destJekyll
	// },

	styles: {
		src: '_pages/**/*.+(scss|sass)',
		dest: '_pages/'
	},

	scripts: {
		src: '_pages/**/*.js',
		dest: '_pages/'
	},

	fonts: {
		src: bower + '**/*.+(eot|ttf|woff|woff2)',
		dest: assetsSrc + 'fonts/'
	},

	images: {
		src: '_pages/**/*.+(jpg|png|svg|gif)',
		dest: '_pages/'
	}
};

var jsLibraries = {

	jquery: {
		src: {
			min: bower + 'jquery/dest/jquery.min.js',
			debug: bower + 'jquery/dest/jquery.js',
		},
		dest: assetsSrc + 'libs-js/'
	},

	semanticUI: {
		src: {
			min: '',
			debug: bower + 'semantic-ui-sass/app/assets/javascripts/semantic-ui.js',
			modular: bower + 'semantic-ui-sass/app/assets/javascripts/semantic-ui/**/*.js'
		},
		dest: assetsSrc + 'libs-js/'
	},

	vue: {
		src: {
			min: bower + 'vue/dist/vue.min.js',
			debug: bower + 'vue/dist/vue.js',
		},
		dest: assetsSrc + 'libs-js/'
	},

	vueX: {
		src: {
			min: bower + 'vue/dist/vuex.min.js',
			debug: bower + 'vue/dist/vuex.js',
		},
		dest: assetsSrc + 'libs-js/'
	},

	vueRouter: {
		src: {
			min: bower + 'vue-router/dist/vue-router.min.js',
			debug: bower + 'vue-router/dist/vue-router.js',
		},
		dest: assetsSrc + 'libs-js/'
	},

	vueResource: {
		src: {
			min: bower + 'vue-resource/dist/vue-resource.min.js',
			debug: bower + 'vue-resource/dist/vue-resource.js',
		},
		dest: assetsSrc + 'libs-js/'
	},
};

var sassLibs = {
	semanticUI: {
		src: {
			min: '',
			debug: bower + 'semantic-ui-sass/app/assets/stylesheets/**/*.+(scss|sass)'
		},
		dest: assetsSrc + 'libs-sass/'
	}
};

var renderedNames = {
	javascript: {
		myJs: 'scripts.js',
		debug: 'libs-debug.js',
		min: 'libs.min.js'
	}
};

var ignoreModernizr = '!' + paths.scripts.src + 'autogenerated/modernizr.js';
var watchedJsFiles = [ignoreModernizr, paths.scripts.src + '**/*.js'];

module.exports = {
	paths: paths,
	jsLibraries: jsLibraries,
	ignoreModernizr: ignoreModernizr,
	watchedJsFiles: watchedJsFiles,
	renderedNames: renderedNames
};
