var assetsSrc = 'assets/';
var bower = assetsSrc + '/_bower_components/';


var paths = {

    html: {
        src: srcJekyll + '**/*.html',
        dest: destJekyll
    },

	styles: {
        src: '_pages/**/*.+(scss|sass)',
        dest: 'pages/'
    },

    scripts: {
        src: '_pages/**/*.js',
        dest: 'pages/'
    },

    fonts: {
        src: bower + '**/*.+(eot|ttf|woff|woff2)',
        dest: assetsDest + 'fonts/'
    },

    images: {
        src: '_pages/**/*.+(jpg|png|svg|gif)',
        dest: 'pages/'
    }
};

var jsLibraries = {

    jquery: {
        min: bower + 'jquery/dest/jquery.min.js',
        debug: bower + 'jquery/dest/jquery.js'
    },

    semanticUI: {
        min: '',
        debug: bower + 'semantic-ui-sass/app/assets/javascripts/semantic-ui.js',
	    modular: bower + 'semantic-ui-sass/app/assets/javascripts/semantic-ui/**/*.js'
    }
};

//var sassLibs = {
//    semanticUI: {
//        min: '',
//        debug: bower + 'semantic-ui-sass/app/assets/stylesheets/**/*.+(scss|sass)'
//    }
//};

var renderedNames = {
	javascript: {
		myJs: 'my-scripts.js',
		debug: 'libraries-debug.js',
		min: 'libraries.min.js'
	}
};

var ignoreModernizr = '!' + paths.scripts.src + 'autogenerated/modernizr.js';
var watchedJsFiles = [ignoreModernizr, paths.scripts.src + '**/*.js'];

module.exports = {
    paths: paths,
    jsLibraries: jsLibraries,
    ignoreModernizr: ignoreModernizr,
    watchedJsFiles: watchedJsFiles,
    renderedNames: renderedNames
};
