var vars = require('./vars'),
	gulp = require('gulp'),
	duplicate = require('gulp-rename'),
	gzip = require('gulp-gzip'),
	localServer = require('gulp-connect'),
	concat = require('gulp-concat'),
	uglifyJs = require('gulp-uglify'),
	plumber = require('gulp-plumber'),
	sourcemaps = require('gulp-sourcemaps'),
	babel = require('gulp-babel'),
	checkJs = require('gulp-jshint');

// for scripts in one folder for the whole project
gulp.task('process-scripts', function() {
	return gulp.src([
		vars.paths.scripts.all.src + 'index.js',
		vars.paths.scripts.all.src + '**/*.js'
	])
	.pipe(plumber())
	.pipe(sourcemaps.init())
	.pipe(babel({
		presets: ['es2015']
	}))
	.pipe(concat(vars.renderedNames.javascript.scripts))
	.pipe(checkJs())
	.pipe(sourcemaps.write())
	.pipe(gulp.dest(vars.paths.scripts.dest))
	.pipe(duplicate({suffix: '.min'}))
	.pipe(uglifyJs())
	.pipe(gulp.dest(vars.paths.scripts.dest))
	.pipe(gzip())
	.pipe(gulp.dest(vars.paths.scripts.dest))
	.pipe(localServer.reload());
});

// javascript file generated for each folder, useful for banners
gulp.task('process-scripts-modular', function() {
	return gulp.src([
		vars.paths.scripts.modular.src
	])
	.pipe(plumber())
	.pipe(babel({
		presets: ['es2015']
	}))
	.pipe(checkJs())
	.pipe(gulp.dest(vars.paths.scripts.modular.dest))
	.pipe(duplicate({suffix: '.min'}))
	.pipe(uglifyJs())
	.pipe(gulp.dest(vars.paths.scripts.modular.dest))
	.pipe(gzip())
	.pipe(gulp.dest(vars.paths.scripts.modular.dest))
	.pipe(localServer.reload());
});

gulp.task('modernizeJs', function() {
	return gulp.src(vars.watchedJsFiles)
	.pipe(modernizeJs())
	.pipe(uglifyJs())
	.pipe(gulp.dest(vars.paths.scripts.src + 'autogenerated/'));
});
