var devel = 'devel/';
var deploy = 'deploy/';
var assetsSrc = devel + 'assets/';
var bower = 'bower_components/';
var offline = assetsSrc + 'offline/';

var paths = {

	deploy: './' + deploy + '/**/*',

	html: {
		src: devel + '/**/*.html',
		dest: deploy
	},

	styles: {
		modular: { // for example banners
			src: devel + '_pages/**/*.+(scss|sass)',
			dest: devel + '_pages/',
			watch: devel + '_pages/**/*.+(scss|sass)'
		},

		all: {
			src: assetsSrc + '_sass/main.scss', // will process only files without prepended underscore
			dest: assetsSrc + 'generated/',
			watch: assetsSrc + '_sass/**/*.+(scss|sass)'
		}
	},

	scripts: {
		modular: {
			src: devel + '_pages/**/*.js',
			dest: devel + '_pages/',
			watch: devel +  '_pages/**/*.js'
		},
		all: {
			src: assetsSrc + '_scripts/',
			dest: assetsSrc + 'generated/',
			watch: assetsSrc + '_scripts/**/*.js'
		}
	},

	sassUtils: {

		bourbon: {
			src: bower + 'bourbon/app/assets/stylesheets/**/*.+(scss|sass)',
			dest: assetsSrc + '_sass/utils/bourbon/'
		},
		normalize: {
			src: bower + 'normalize-scss/sass/**/*.+(scss|sass)',
			dest: assetsSrc + '_sass/utils/normalize/'
		}
	},

	libs: {
		jquery: {
			src: bower + 'jquery/dist/jquery.min.js',
			dest: offline
		},

		jquerySlim: {
			src: bower + 'jquery/dist/jquery.slim.min.js',
			dest: offline
		},

		semantic: {
			src: bower + 'semantic/dist/**/*',
			dest: offline + 'semantic',
			js: bower + 'semantic/dist/semantic.min.js'
		},

		vue: {
			src: bower + 'vue/dist/vue.min.js',
			dest: offline
		},

		vueX: {
			src: bower + 'vuex/dist/vuex.min.js',
			dest: offline
		},

		vueRouter: {
			src: bower + 'vue-router/dist/vue-router.min.js',
			dest: offline
		},

		vueResource: {
			src: bower + 'vue-resource/dist/vue-resource.min.js',
			dest: offline
		},

		gsap: {
			src: bower + 'gsap/src/minified/**/*.js',
			dest: offline + 'gsap/'
		}
	},

	merged: {
		dest: offline + 'merged/'
	}
};


var renderedNames = {
	javascript: {

		/* MY MERGED JAVASCRIPT */
		scripts: 'scripts.js',

		/* MERGED LIBS */
		semantic:'semantic.min.js',
		vue: 'vue.min.js',
		banners: 'banner.js',
		all: 'libs.min.js'
	}
};

var ignoreModernizr = '!' + paths.scripts.all.src + 'autogenerated/modernizr.js';
var watchedJsFiles = [ignoreModernizr, paths.scripts.all.src];

module.exports = {
	paths: paths,
	ignoreModernizr: ignoreModernizr,
	watchedJsFiles: watchedJsFiles,
	renderedNames: renderedNames
};
