const devel = 'devel/';
const deploy = 'deploy/';
const assetsSrc = `${devel}assets/`;
const bower = 'bower_components/';
const offline = `${assetsSrc}offline/`;

const paths = {

	deploy: `./${deploy}**/*`,

	delete: {
		development: [
			`${offline}**/*`,
			`${assetsSrc}_sass/utils/**/*`,
			`!${assetsSrc}_sass/utils/_utils.scss`,
			`${assetsSrc}generated/**/*`,
			`${deploy}**/*`,
			`${deploy}.htaccess`
		],
		production: [
			`${assetsSrc}generated/main.css`,
			`${assetsSrc}generated/scripts.js`
		]
	},


	html: {
		src: `${devel}**/*.html`,
		dest: deploy
	},

	styles: {

		all: {
			src: `${assetsSrc}_sass/main.scss`,
			dest: `${assetsSrc}generated/`,
			watch: `${assetsSrc}_sass/**/*.+(scss|sass)`
		}
	},

	scripts: {
		all: {
			src: `${assetsSrc}_scripts/`,
			dest: `${assetsSrc}generated/`,
			watch: `${assetsSrc}_scripts/**/*.js`
		}
	},

	sassUtils: {

		bourbon: {
			src: `${bower}bourbon/app/assets/stylesheets/**/*.+(scss|sass)`,
			dest: `${assetsSrc}_sass/utils/bourbon/`
		},
		normalize: {
			src: `${bower}normalize-scss/sass/**/*.+(scss|sass)`,
			dest: `${assetsSrc}_sass/utils/normalize/`
		}
	},

	libs: {
		jquery: {
			src: `${bower}jquery/dist/jquery.min.js`,
			dest: offline
		},

		jquerySlim: {
			src: `${bower}jquery/dist/jquery.slim.min.js`,
			dest: offline
		},

		semantic: {
			src: `${bower}semantic/dist/**/*`,
			dest: `${offline}semantic`,
			js: `${bower}semantic/dist/semantic.min.js`
		},

		gsap: {
			src: `${bower}gsap/src/minified/**/*.js`,
			dest: `${offline}gsap/`
		}
	},

	merged: {
		dest: `${offline}merged/`
	}
};


const renderedNames = {
	javascript: {

		/* MY MERGED JAVASCRIPT */
		scripts: 'scripts.js',

		/* MERGED LIBS */
		semantic: 'semantic.min.js',
		all: 'libs.min.js'
	}
};

const ignoreModernizr = `!${paths.scripts.all.src}autogenerated/modernizr.js`;
const watchedJsFiles = [ignoreModernizr, paths.scripts.all.src];
const filterObject = (obj,newObj, exclude) => {
	Object.keys(obj).forEach(function (key) {
		if (key !== exclude) {
			if (typeof(obj[key]) === "object") {
				newObj[key] = {};
				filterObject(obj[key],newObj[key]);
			} else {
				newObj[key] = obj[key];
			}
		}
	});
};

export {paths, ignoreModernizr, watchedJsFiles, renderedNames, filterObject};