var devel = 'devel/';
var deploy = 'deploy/';
var assetsSrc = devel + 'assets/';
var bower = 'bower_components/';
var offline = assetsSrc + 'offline/';
var banners = devel + '_pages/'

var paths = {

	deploy: './' + deploy + '/**/*',

	html: {
		src: devel + '/**/*.html',
		dest: deploy
	},

	styles: {
		banners: { // for example banners
			src: banners + '**/*.+(scss|sass)',
			dest: banners,
			watch: banners + '**/*.+(scss|sass)'
		},

		all: {
			src: assetsSrc + '_sass/main.scss',
			dest: assetsSrc + 'generated/',
			watch: assetsSrc + '_sass/**/*.+(scss|sass)'
		}
	},

	scripts: {
		banners: {
			src: banners + '**/*.js',
			dest: banners,
			watch: banners + '**/*.js'
		},
		all: {
			src: assetsSrc + '_scripts/',
			dest: assetsSrc + 'generated/',
			watch: assetsSrc + '_scripts/**/*.js'
		}
	},

	sassUtils: {

		bourbon: {
			src: bower + 'bourbon/app/assets/stylesheets/**/*.+(scss|sass)',
			dest: assetsSrc + '_sass/utils/bourbon/'
		},
		normalize: {
			src: bower + 'normalize-scss/sass/**/*.+(scss|sass)',
			dest: assetsSrc + '_sass/utils/normalize/'
		}
	},

	libs: {
		jquery: {
			src: bower + 'jquery/dist/jquery.min.js',
			dest: offline
		},

		jquerySlim: {
			src: bower + 'jquery/dist/jquery.slim.min.js',
			dest: offline
		},

		semantic: {
			src: bower + 'semantic/dist/**/*',
			dest: offline + 'semantic',
			js: bower + 'semantic/dist/semantic.min.js'
		},

		gsap: {
			src: bower + 'gsap/src/minified/**/*.js',
			dest: offline + 'gsap/'
		}
	},

	merged: {
		dest: offline + 'merged/'
	}
};


var renderedNames = {
	javascript: {

		/* MY MERGED JAVASCRIPT */
		scripts: 'scripts.js',

		/* MERGED LIBS */
		semantic:'semantic.min.js',
		all: 'libs.min.js'
	}
};

var ignoreModernizr = '!' + paths.scripts.all.src + 'autogenerated/modernizr.js';
var watchedJsFiles = [ignoreModernizr, paths.scripts.all.src];

module.exports = {
	paths: paths,
	ignoreModernizr: ignoreModernizr,
	watchedJsFiles: watchedJsFiles,
	renderedNames: renderedNames
};
